name: My First Workflow
on: [push]

jobs:
  MyFirstActionInAction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Run my container
      id: lokessri_container
      uses: ./
      with:
        who-to-greet: '@wulfland'
    
    - name: Get the output
      run: echo "The answer was ${{ steps.lokessri_container.outputs.answer }}"

    - name: Test the container
      if: ${{ steps.lokessri_container.outputs.answer != 42 }}
      run: |
        echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
        exit 1